import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#021f2e",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#ebeef0",
        "primary-fixed": "#cfe5f7",
        "secondary-fixed-dim": "#ffb2b7",
        "surface": "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-container-high": "#e5e9eb",
        "primary-container": "#081f2c",
        "on-background": "#181c1e",
        "on-secondary-fixed": "#40000d",
        "on-primary-fixed": "#071e2b",
        "outline": "#73787c",
        "on-primary-fixed-variant": "#344958",
        "on-surface-variant": "#43474b",
        "on-primary-container": "#728898",
        "outline-variant": "#c3c7cc",
        "secondary": "#ba0037",
        "tertiary-fixed": "#cce6fa",
        "surface-tint": "#4c6170",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#b0cadd",
        "secondary-fixed": "#ffdadb",
        "inverse-on-surface": "#eef1f3",
        "surface-container-low": "#f1f4f6",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#b3c9db",
        "inverse-primary": "#b3c9db",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#920029",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#6f889a",
        "on-surface": "#181c1e",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f7fafc",
        "background": "#f7fafc",
        "on-tertiary-fixed": "#011e2d",
        "on-tertiary-fixed-variant": "#314a5a",
        "primary": "#000306",
        "on-secondary-container": "#fffbff",
        "secondary-container": "#e70648",
        "tertiary": "#000205",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
