import { ContractAnalysis } from "@/types/contract";

export const DEMO_ANALYSIS: ContractAnalysis = {
  metadata: {
    contractTitle: "Master Services Agreement — Global Tech Solutions Ltd. & Meridian Financial Group plc",
    agreementType: "Master Services Agreement (MSA)",
    parties: [
      { name: "Global Tech Solutions Ltd.", role: "Vendor / Service Provider" },
      { name: "Meridian Financial Group plc", role: "Client" },
    ],
    effectiveDate: "January 12, 2024",
    expirationDate: "January 11, 2027 (end of Initial Term)",
    renewalTerms: "Automatic renewal for successive 2-year periods unless 180 days' written notice of non-renewal is provided",
    noticePeriod: "180 days for non-renewal; 30 days for termination for cause; 90 days for termination for convenience",
    governingLaw: "Laws of England and Wales",
    jurisdiction: "Courts of England and Wales (subject to LCIA arbitration for disputes)",
    contractValue: "£250,000 per annum base retainer; additional hours at £350/hour",
    currency: "GBP (£)",
    paymentTerms: "Invoices due within 30 days of receipt; quarterly in advance for base retainer; late interest at 8% p.a. above Bank of England base rate",
    fees: "£250,000 p.a. base retainer; £350/hour for additional development",
    terminationTerms: "For cause: 30 days notice (uncured material breach); For convenience: 90 days notice by Client only",
    liabilityCap: "Greater of 3x total fees paid in preceding 12 months or £2,000,000 — EXCEPT IP infringement claims which are UNLIMITED",
    indemnification: "Vendor indemnifies Client for breach, negligence, IP infringement, and data breaches. Client indemnifies Vendor for misuse of Deliverables.",
    confidentiality: "5-year post-termination obligation; standard exclusions apply",
    ipOwnership: "Deliverables are works made for hire owned by Client (upon full payment). Vendor retains pre-existing IP and a royalty-free licence to anonymised learnings.",
    privacyDataProtection: "UK GDPR compliant; DPA required; 36-hour breach notification; no EEA transfers without consent and safeguards",
    securityObligations: "Appropriate technical and organisational measures; annual third-party security audits shared with Client on request",
    auditRights: "Client may audit Vendor books, records, and systems with 10 business days notice; once per year (more if material breach suspected)",
    assignment: "Neither party may assign without prior written consent (not to be unreasonably withheld); exceptions for affiliates and M&A",
    disputeResolution: "Three-stage: senior management escalation (30 days) → CEDR mediation (non-binding) → LCIA arbitration (sole arbitrator, London, English)",
  },
  riskAnalysis: {
    overallRiskScore: 78,
    riskLevel: "HIGH",
    risks: [
      {
        title: "Unlimited IP Liability Exposure",
        severity: "CRITICAL",
        explanation: "Clause 14.3 creates unlimited liability for IP infringement claims by carving them out from the general £2M cap. This is an exceptional and highly unusual departure from standard MSA practice and exposes the Client to uncapped claims from Vendor.",
        clause: "Clause 14.3",
        recommendedAction: "Negotiate a specific cap for IP indemnity claims (suggested: 2x total contract value or £5M, whichever is greater). Escalate to General Counsel and Finance before execution.",
      },
      {
        title: "Automatic 2-Year Renewal with 180-Day Notice Window",
        severity: "HIGH",
        explanation: "The agreement auto-renews for 2-year terms requiring 180 days (6 months) advance written notice to prevent renewal. This is an unusually long notice period that creates significant lock-in risk if not actively tracked.",
        clause: "Clause 4.2",
        recommendedAction: "Add to contract management calendar immediately. Consider negotiating the notice period down to 90 days, which is more standard for MSAs of this value.",
      },
      {
        title: "Vendor Royalty-Free Licence to Anonymised Learnings",
        severity: "HIGH",
        explanation: "Clause 5.4 grants Vendor a perpetual royalty-free licence to use 'anonymised learnings and methodologies' from the engagement. In a financial services context, this may include sensitive business logic or competitive intelligence even when 'anonymised'.",
        clause: "Clause 5.4",
        recommendedAction: "Request deletion of Clause 5.4 or narrowly define 'anonymised learnings' to exclude all financial models, trading strategies, and business processes. Legal and Compliance review required.",
      },
      {
        title: "Missing Executed Exhibits",
        severity: "HIGH",
        explanation: "Exhibits A (Statement of Work), B (Data Processing Agreement), and C (Pricing Matrix) are referenced but not attached. The DPA is particularly critical for UK GDPR compliance; the agreement cannot legally process personal data without it.",
        clause: "Agreement footer; Clause 7",
        recommendedAction: "Do not execute this Agreement until all Exhibits are finalised and attached. DPA must be in place before any data processing commences.",
      },
      {
        title: "Client-Only Termination for Convenience",
        severity: "MEDIUM",
        explanation: "Only Client has the right to terminate for convenience (Clause 8.2). Vendor has no equivalent right, which is actually favourable to Client but creates a potentially imbalanced commercial relationship that may affect Vendor's willingness to invest in the engagement.",
        clause: "Clause 8.2",
        recommendedAction: "Acceptable as drafted from Client's perspective. Note in matter record.",
      },
      {
        title: "36-Hour Data Breach Notification (Shorter than Statutory)",
        severity: "MEDIUM",
        explanation: "Clause 7.4 requires Vendor to notify Client of a Personal Data Breach within 36 hours. UK GDPR requires notification to the ICO within 72 hours of awareness. The 36-hour contractual window exceeds the statutory standard and may be operationally challenging for Vendor.",
        clause: "Clause 7.4",
        recommendedAction: "Confirm Vendor can operationally meet this timeline. This is favourable to Client from a compliance perspective but should be acknowledged as a tight SLA.",
      },
      {
        title: "Late Payment Interest Rate",
        severity: "LOW",
        explanation: "Interest on late payments accrues at 8% above Bank of England base rate. With current base rates, this could result in very high effective interest rates on overdue invoices.",
        clause: "Clause 3.5",
        recommendedAction: "Ensure prompt payment processes are in place to avoid triggering this clause. Consider negotiating a fixed rate of 4-6% above base.",
      },
    ],
  },
  executiveSummary:
    "This Master Services Agreement governs a significant technology services engagement between Global Tech Solutions Ltd. (Vendor) and Meridian Financial Group plc (Client), with a base annual value of £250,000 over an initial 3-year term. The agreement is broadly well-structured but contains several provisions of material concern. Most critically, Clause 14.3 imposes unlimited liability on the Vendor for IP infringement claims — an unusual carve-out that warrants negotiation before execution. The 180-day auto-renewal notice window and the absence of the three referenced Exhibits (SOW, DPA, Pricing Matrix) are also significant issues requiring resolution prior to signature. The data protection provisions are generally robust and exceed statutory minimums. Legal review and negotiation of at least 3 clauses is recommended before execution.",
  keyObligations: [
    "Client must provide written non-renewal notice at least 180 days before end of any term",
    "Client must pay base retainer of £250,000 p.a. quarterly in advance",
    "Client must pay invoices within 30 days to avoid interest accrual",
    "Vendor must maintain Professional Indemnity, Cyber Liability, and Public Liability insurance throughout the term",
    "Vendor must appoint a Data Protection Officer and maintain processing records",
    "Vendor must notify Client of any Personal Data Breach within 36 hours",
    "Vendor must undergo annual third-party security audits and share results with Client",
    "Both parties must escalate disputes to senior management before initiating formal proceedings",
  ],
  keyDates: [
    { label: "Effective Date", date: "January 12, 2024" },
    { label: "Initial Term End", date: "January 11, 2027" },
    { label: "First Renewal Notice Deadline", date: "July 15, 2026 (180 days before Jan 11, 2027)" },
    { label: "Next Auto-Renewal (if no notice)", date: "January 12, 2027" },
    { label: "Second Renewal End (if renewed)", date: "January 11, 2029" },
  ],
  top3Risks: [
    {
      title: "Unlimited IP Liability Exposure",
      severity: "CRITICAL",
      explanation: "Clause 14.3 creates unlimited liability for IP infringement claims by carving them out from the general £2M cap. This is an exceptional and highly unusual departure from standard MSA practice.",
      clause: "Clause 14.3",
      recommendedAction: "Negotiate a specific cap for IP indemnity claims. Escalate to General Counsel and Finance before execution.",
    },
    {
      title: "Automatic 2-Year Renewal with 180-Day Notice Window",
      severity: "HIGH",
      explanation: "The agreement auto-renews for 2-year terms requiring 180 days advance written notice to prevent renewal — an unusually long notice period creating significant lock-in risk.",
      clause: "Clause 4.2",
      recommendedAction: "Add to contract management calendar immediately. Negotiate notice period down to 90 days.",
    },
    {
      title: "Missing Executed Exhibits (SOW, DPA, Pricing)",
      severity: "HIGH",
      explanation: "Three critical exhibits are referenced but not attached. The DPA is required for UK GDPR compliance; the agreement cannot legally process personal data without it.",
      clause: "Agreement footer; Clause 7",
      recommendedAction: "Do not execute until all Exhibits are finalised. DPA must be in place before any data processing commences.",
    },
  ],
  missingInformation: [
    "Exhibit A (Statement of Work #1) — not attached",
    "Exhibit B (Data Processing Agreement) — not attached; required for UK GDPR compliance",
    "Exhibit C (Pricing Matrix) — not attached",
    "Client signatory name and signature — blank in signature block",
    "Vendor signatory name and signature — blank in signature block",
  ],
  unusualClauses: [
    "Clause 14.3: Unlimited liability carve-out for IP infringement claims is highly unusual in technology MSAs and significantly exceeds market standard",
    "Clause 5.4: Vendor's perpetual royalty-free licence to 'anonymised learnings' is uncommon and potentially risks competitive intelligence leakage in a financial services context",
    "Clause 7.4: 36-hour breach notification requirement is more stringent than UK GDPR's 72-hour statutory standard — operationally demanding for Vendor",
    "Clause 4.2: 180-day auto-renewal notice period is double the typical 90-day market standard for MSAs of this type and value",
  ],
  recommendedLegalRouting: "Procurement & Finance (liability cap negotiation) → Legal — Commercial (IP and Exhibits review) → Compliance / DPO (DPA and UK GDPR review) → General Counsel sign-off before execution",
  disclaimer:
    "This is AI-assisted analysis for informational purposes only and does not constitute legal advice. All findings should be reviewed by qualified legal counsel before any action is taken.",
};
